# This file was added by Pulumi and should not be edited manually. To edit the contents of this file, please go
# to the github-management project in moneymeets-pulumi and call `pulumi up` after changing the template file.

name: Merge checks

on:
  push:
    branches:
      - feature/*
  pull_request_target:

jobs:
  merge-checks:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Get head commit hash
        id: get_head_hash
        uses: moneymeets/moneymeets-composite-actions/select-conditionally@feature/add-select-conditionally-composite-action
        with:
            condition: ${{ github.event_name == 'pull_request_target' }}
            if_condition_true: ${{ github.event.pull_request.head.sha }}
            if_condition_false: ${{ github.sha }}
      - name: Merge checks
        uses: moneymeets/action-merge-checks@feature/MD-6273-use-github-api-to-get-list-of-commits
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_head_sha: ${{ steps.get_head_hash.outputs.value }}
